### Preprocessing

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split

In [1]:
# from numpy import array
# from numpy import argmax
# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import OneHotEncoder
# define example
def list2onehot(my_list):
    #my_list = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm']
    values = array(my_list)
    #print(values)
    # integer encode
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)
    #print(integer_encoded)
    # binary encode
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    #print(onehot_encoded)
    
    # invert to retrieve first example from integer/onehot
    #inverted = label_encoder.inverse_transform(integer_encoded[0])
    #inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])    
    #print(inverted)
    return integer_encoded, onehot_encoded

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
list2onehot(data)


(array([[0],
        [0],
        [2],
        [0],
        [1],
        [1],
        [2],
        [0],
        [2],
        [1]], dtype=int64), array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]))

In [ ]:
# Splitting dataset
# second way to split (using a sklearn method)
# we are getting 3 sets: Train(50%), development(25%) and test(25%) ; %amount of data
X_train, X_dev, y_train, y_dev = train_test_split(train_embedvec, indices, 
                                                  test_size=0.25, stratify=indices,
                                                  random_state=seed)

X_dev, X_test, y_dev, y_test = train_test_split(X_dev, y_dev,
                                                test_size=0.5, stratify=y_dev,
                                                random_state=seed)}
0Dmodel.fit(X_train, y_train, validation_data=(X_dev,y_dev), epochs=150, batch_size=10)

### Testing

In [ ]:
from sklearn.metrics import *

In [ ]:
# about metrics/scorer
#from sklearn.metrics import *
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

In [2]:
# summary about layer and parameters
print(model.summary())

NameError: name 'model' is not defined

### Enviroment

In [ ]:
# choose enviroment 
"using command line go to scripts directory and type: activate <myenv>"

##################################################### use pip in your current enviroment
import pip

# check packages
packages = [package.project_name for package in pip.get_installed_distributions()]
print('\n'.join(str(x) for x in packages))
"numpy" in packages	
		
def pip_install(package):
    pip.main(['install', package])	
	
# -*- coding: utf-8 -*-

### numpy

In [3]:
#group by a vector and count
import numpy as np
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
