In [6]:
import numpy as np

arr = np.array([1, 3, 2, 4, 5])

print(arr)
print(arr.argsort())
print(arr.argsort()[-3:])
print(arr.argsort()[::-1])
print(arr.argsort()[-3:][::-1])

[1 3 2 4 5]
[0 2 1 3 4]
[1 3 4]
[4 3 1 2 0]
[4 3 1]


In [3]:
??arr.argsort